spring:
  application:
    name: "choerbli"
  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: false
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/choerbli_db
    username: template
    password: secret
logging:
  level:
    org.choerbli: debug
    org.flywaydb.core: debug
    root: info