version: '3.8'
services:
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: template
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: choerbli_db
    ports:
      - "5430:5432"
    expose:
      - "5432"

  choerbli:
    container_name: choerbli
    build: ../.
    ports:
      - "8080:8080"
    restart: always
    environment:
      HOST: database
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - database